/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JuanDaza.Farmacia;

import javax.swing.JFrame;
import javax.swing.SwingConstants;

/**
 *
 * @author juand
 */
public class VentanaFactura extends javax.swing.JFrame {

    /**
     * Creates new form VentanaFactura
     */
    public VentanaFactura(String medicamento, String tipo,
            String cantidad, String distribuidor, String sucursal) {
        initComponents();
        setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        MedLabel.setText(medicamento);
        TipLabel.setText(tipo);
        CantLabel.setHorizontalAlignment(SwingConstants.RIGHT);
        CantLabel.setText(cantidad);
        DistriLabel.setText(distribuidor);
        DirLabel.setText(sucursal);
        
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Back_factura = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DistriLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        DirLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CantLabel = new javax.swing.JLabel();
        TipLabel = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        MedLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 500));

        Back_factura.setBackground(new java.awt.Color(255, 255, 255));
        Back_factura.setPreferredSize(new java.awt.Dimension(400, 500));
        Back_factura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel1.setText("========================================");
        Back_factura.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jLabel2.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel2.setText("DETALLES DEL PEDIDO");
        Back_factura.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 125, -1, -1));

        DistriLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        DistriLabel.setToolTipText("");
        DistriLabel.setPreferredSize(new java.awt.Dimension(160, 15));
        Back_factura.add(DistriLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 162, -1, -1));

        jLabel4.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel4.setText("Especializacion en");
        Back_factura.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        jLabel5.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel5.setText("Ing. de Software");
        Back_factura.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, -1));

        jLabel6.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel6.setText("========================================");
        Back_factura.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel7.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel7.setText("Desarrollo: Juan D. Daza");
        Back_factura.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        jLabel8.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel8.setText("DETALLE DE ENVIO");
        Back_factura.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel9.setText("Para la farmacia situada en: ");
        Back_factura.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 285, -1, -1));

        DirLabel.setFont(new java.awt.Font("Rockwell", 1, 15)); // NOI18N
        DirLabel.setPreferredSize(new java.awt.Dimension(500, 15));
        Back_factura.add(DirLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 305, 350, -1));

        jLabel11.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel11.setText("unidades de ");
        Back_factura.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 207, -1, -1));

        jLabel3.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel3.setText("========================================");
        Back_factura.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel12.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel12.setText("UNIR");
        Back_factura.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));

        CantLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        CantLabel.setPreferredSize(new java.awt.Dimension(120, 15));
        Back_factura.add(CantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 209, -1, -1));

        TipLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        TipLabel.setPreferredSize(new java.awt.Dimension(150, 15));
        Back_factura.add(TipLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 209, -1, -1));

        jLabel10.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel10.setText("Pedido al Distribuidor : ");
        Back_factura.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        MedLabel.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        MedLabel.setPreferredSize(new java.awt.Dimension(80, 15));
        Back_factura.add(MedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 232, -1, -1));

        jLabel13.setFont(new java.awt.Font("Rockwell", 1, 14)); // NOI18N
        jLabel13.setText("Facturacion Farmacia");
        Back_factura.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setText("CANCELAR");
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Back_factura.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 110, 20));

        jButton3.setBackground(new java.awt.Color(153, 255, 153));
        jButton3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton3.setText("CONFIRMAR");
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Back_factura.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Back_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Back_factura, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.out.println("Pedido enviado");       // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Back_factura;
    private javax.swing.JLabel CantLabel;
    private javax.swing.JLabel DirLabel;
    private javax.swing.JLabel DistriLabel;
    private javax.swing.JLabel MedLabel;
    private javax.swing.JLabel TipLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
