/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.JuanDaza.Farmacia;

import java.awt.Color;
import java.awt.Font;


/**
 *
 * @author juand
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoDistribuidor = new javax.swing.ButtonGroup();
        Fondo = new javax.swing.JPanel();
        CanTextField = new javax.swing.JTextField();
        DistribLabel = new javax.swing.JLabel();
        TypeMedLabel = new javax.swing.JLabel();
        TypeMedComBox = new javax.swing.JComboBox<>();
        buttonConfir = new javax.swing.JButton();
        AuxLabelMed = new javax.swing.JLabel();
        NombreLabel1 = new javax.swing.JLabel();
        MedTextField = new javax.swing.JTextField();
        AuxCantLabel = new javax.swing.JLabel();
        CantidadLabel = new javax.swing.JLabel();
        OpcCemefar = new javax.swing.JRadioButton();
        OpcCofarma = new javax.swing.JRadioButton();
        OpcEmpsephar = new javax.swing.JRadioButton();
        AuxDistLabel = new javax.swing.JLabel();
        AuxDistrLabel = new javax.swing.JLabel();
        DistribLabel1 = new javax.swing.JLabel();
        OpcSecundaria = new javax.swing.JCheckBox();
        OpcPrincipal = new javax.swing.JCheckBox();
        AuxSucurLabel = new javax.swing.JLabel();
        BotonBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Fondo.setBackground(new java.awt.Color(255, 255, 255));
        Fondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CanTextField.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        CanTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        CanTextField.setDoubleBuffered(true);
        CanTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CanTextFieldMousePressed(evt);
            }
        });
        CanTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanTextFieldActionPerformed(evt);
            }
        });
        Fondo.add(CanTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 290, -1));

        DistribLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        DistribLabel.setText("Sucursal");
        Fondo.add(DistribLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 20));

        TypeMedLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        TypeMedLabel.setText("Tipo del medicamento");
        Fondo.add(TypeMedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, 20));

        TypeMedComBox.setFont(new java.awt.Font("Roboto", 2, 14)); // NOI18N
        TypeMedComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Analgésico", "Analéptico", "Anestésico", "Antiácido", "Antidepresivo ", "Antibióticos" }));
        TypeMedComBox.setBorder(null);
        TypeMedComBox.setPreferredSize(new java.awt.Dimension(150, 30));
        Fondo.add(TypeMedComBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        buttonConfir.setBackground(new java.awt.Color(153, 255, 153));
        buttonConfir.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        buttonConfir.setText("Confirmar");
        buttonConfir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        buttonConfir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonConfirActionPerformed(evt);
            }
        });
        Fondo.add(buttonConfir, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 130, -1));

        AuxLabelMed.setBackground(new java.awt.Color(255, 0, 0));
        AuxLabelMed.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        AuxLabelMed.setForeground(new java.awt.Color(255, 0, 0));
        AuxLabelMed.setPreferredSize(new java.awt.Dimension(200, 20));
        Fondo.add(AuxLabelMed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, -1));

        NombreLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        NombreLabel1.setText("Nombre del medicamento ");
        Fondo.add(NombreLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, 20));

        MedTextField.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        MedTextField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        MedTextField.setDoubleBuffered(true);
        MedTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                MedTextFieldMousePressed(evt);
            }
        });
        MedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedTextFieldActionPerformed(evt);
            }
        });
        Fondo.add(MedTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 290, -1));

        AuxCantLabel.setForeground(new java.awt.Color(255, 0, 0));
        AuxCantLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        Fondo.add(AuxCantLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        CantidadLabel.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        CantidadLabel.setText("Cantidad producto");
        Fondo.add(CantidadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, 20));

        GrupoDistribuidor.add(OpcCemefar);
        OpcCemefar.setText("Cemefar");
        OpcCemefar.setToolTipText("");
        OpcCemefar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcCemefarActionPerformed(evt);
            }
        });
        Fondo.add(OpcCemefar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, -1, -1));

        GrupoDistribuidor.add(OpcCofarma);
        OpcCofarma.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        OpcCofarma.setText("Cofarma");
        OpcCofarma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcCofarmaActionPerformed(evt);
            }
        });
        Fondo.add(OpcCofarma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        GrupoDistribuidor.add(OpcEmpsephar);
        OpcEmpsephar.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        OpcEmpsephar.setText("Empsephar ");
        OpcEmpsephar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcEmpsepharActionPerformed(evt);
            }
        });
        Fondo.add(OpcEmpsephar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, -1, -1));

        AuxDistLabel.setForeground(new java.awt.Color(255, 0, 0));
        AuxDistLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        Fondo.add(AuxDistLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        AuxDistrLabel.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        AuxDistrLabel.setForeground(new java.awt.Color(255, 0, 0));
        AuxDistrLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        Fondo.add(AuxDistrLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));

        DistribLabel1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        DistribLabel1.setText("Distribuidor");
        Fondo.add(DistribLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        OpcSecundaria.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        OpcSecundaria.setText("Secundaria");
        OpcSecundaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcSecundariaActionPerformed(evt);
            }
        });
        Fondo.add(OpcSecundaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 450, -1, -1));

        OpcPrincipal.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        OpcPrincipal.setText("Principal");
        OpcPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpcPrincipalActionPerformed(evt);
            }
        });
        Fondo.add(OpcPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        AuxSucurLabel.setPreferredSize(new java.awt.Dimension(200, 20));
        Fondo.add(AuxSucurLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, -1, -1));

        BotonBorrar.setBackground(new java.awt.Color(255, 51, 51));
        BotonBorrar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        BotonBorrar.setText("Borrar");
        BotonBorrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        BotonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarActionPerformed(evt);
            }
        });
        Fondo.add(BotonBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fondo, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        Fondo.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonConfirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonConfirActionPerformed
        
        //declaracion de variables
        String medicamentoLabel = MedTextField.getText(); 
        String cantidadMedi = CanTextField.getText();
        String tipoMedicamento = (String) TypeMedComBox.getSelectedItem();
        boolean seleCemefar = OpcCemefar.isSelected();      
        boolean seleEmpsephar = OpcEmpsephar.isSelected(); 
        boolean seleCofarma = OpcCofarma.isSelected(); 
        boolean selePrincipal = OpcPrincipal.isSelected();
        boolean seleSecundaria = OpcSecundaria.isSelected();
       
        
        
        // inicializacion
        AuxLabelMed.setText("");
        AuxCantLabel.setText("");
        AuxDistrLabel.setText("");
        AuxSucurLabel.setText("");
        
        
        //Impresion cabecera impresion
        System.out.println("**********************************");
        
        
        ValidationResult resultado = valMedicamento(medicamentoLabel);
        
        String medicamento = resultado.getMedicamento();
        String errorMed = resultado.getErrorMed();
        System.out.println(medicamento);
        System.out.println(errorMed);
        
        
        
        valCantidad(cantidadMedi);//Validacion Cantidad
        valDistribuidor(seleCemefar,seleEmpsephar,
                seleCofarma);//  //Validacion Distribuidor
        valSucursal(selePrincipal,seleSecundaria);//Validacion Sucursal
                
    }//GEN-LAST:event_buttonConfirActionPerformed

    private void CanTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanTextFieldActionPerformed

    private void CanTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CanTextFieldMousePressed
          CanTextField.setText("");      // TODO add your handling code here:
    }//GEN-LAST:event_CanTextFieldMousePressed

    private void MedTextFieldMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MedTextFieldMousePressed
        MedTextField.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_MedTextFieldMousePressed

    private void MedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedTextFieldActionPerformed

    private void OpcCofarmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcCofarmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcCofarmaActionPerformed

    private void OpcEmpsepharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcEmpsepharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcEmpsepharActionPerformed

    private void OpcCemefarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcCemefarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcCemefarActionPerformed

    private void OpcSecundariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcSecundariaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcSecundariaActionPerformed

    private void OpcPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpcPrincipalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpcPrincipalActionPerformed

    private void BotonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarActionPerformed
        iniciaComponents();
    }//GEN-LAST:event_BotonBorrarActionPerformed
       
    public void iniciaComponents(){
        AuxLabelMed.setText("");
        AuxCantLabel.setText("");
        AuxDistrLabel.setText("");
        AuxSucurLabel.setText("");
        MedTextField.setText("");
        CanTextField.setText("");
        TypeMedComBox.setSelectedItem("Analgésico");
        GrupoDistribuidor.clearSelection();
        OpcPrincipal.setSelected(false);
        OpcSecundaria.setSelected(false);
        
    }
    
    public class ValidationResult {
        private String medicamento;
        private String errorMed;

        public ValidationResult(String medicamento, String errorMed) {
            this.medicamento = medicamento;
            this.errorMed = errorMed;
        }

        public String getMedicamento() {
            return medicamento;
        }

        public String getErrorMed() {
            return errorMed;
        }
    }   

    public ValidationResult valMedicamento(String medicamento) {
        String errorMed;

        if (medicamento.isEmpty()) {
            AuxLabelMed.setText("Debe ingresar un medicamento");
            errorMed = "1";
        } else {
            errorMed = "0";
        }

        return new ValidationResult(medicamento, errorMed);
    }
    
    /*public String valMedicamento(String medicamento){
         String errorMed = "0";
         if(medicamento.isEmpty()){
            AuxLabelMed.setText("Debe ingresar un medicamento");
            errorMed = "-1";
            
        }else{
            errorMed = medicamento;
            
        }
        return errorMed;
        
    }*/
    
    public void valCantidad(String cantidad){
        double cantInt = 0;
        
        if(cantidad.isEmpty()){
           AuxCantLabel.setText("Debe ingresar la cantidad"); 
                   
        } else{
            try {
                 cantInt = Double.parseDouble(cantidad);
                 
                  
            }catch(NumberFormatException ex){
                AuxCantLabel.setText("La cantidad debe ser numerica");
                
            }
        }
        if(cantInt < 0){
                AuxCantLabel.setText("La cantidad debe ser positiva");
                CanTextField.setText("0");
               
        }
    }
    
    public void valDistribuidor(boolean cemefar,boolean empsephar, 
                boolean cofarma){
        if(cemefar){
            AuxDistrLabel.setFont(new Font("Roboto", Font.ITALIC, 14));
            AuxDistrLabel.setForeground(Color.black);
            AuxDistrLabel.setText("Escogio Cemefar");            
        }else if(empsephar){
            AuxDistrLabel.setFont(new Font("Roboto", Font.PLAIN, 14));
            AuxDistrLabel.setForeground(Color.black);
            AuxDistrLabel.setText("Escogio Empsephar");
        }else if (cofarma){
            AuxDistrLabel.setFont(new Font("Roboto", Font.PLAIN, 14));
            AuxDistrLabel.setForeground(Color.black);
            AuxDistrLabel.setText("Escogio Cemefar");
        }else if(OpcCofarma.isSelected()){
            AuxDistrLabel.setFont(new Font("Roboto", Font.PLAIN, 14));
            AuxDistrLabel.setForeground(Color.black);
            AuxDistrLabel.setText("Escogio Cofarma");            
        }else{    
            AuxDistrLabel.setFont(new Font("Roboto", Font.PLAIN, 14));
            AuxDistrLabel.setForeground(Color.red);
            AuxDistrLabel.setText("Debe escoger un Distribuidor");
            }
        }
    
    public void valSucursal(boolean selePrincipal, boolean seleSecundaria){
        if(selePrincipal && seleSecundaria){
            AuxSucurLabel.setFont(new Font("Roboto", Font.PLAIN, 14));
            AuxSucurLabel.setForeground(Color.black);
            AuxSucurLabel.setText("Envio a ambas sucursales");    
        }else if(selePrincipal){
            AuxSucurLabel.setFont(new Font("Roboto", Font.PLAIN, 14));
            AuxSucurLabel.setForeground(Color.black);
            AuxSucurLabel.setText("Envio Sucursal Principal");   
        }else if(seleSecundaria){
            AuxSucurLabel.setFont(new Font("Roboto", Font.PLAIN, 14));
            AuxSucurLabel.setForeground(Color.black);
            AuxSucurLabel.setText("Envio Sucursal Secundaria");  
        }else{
            AuxSucurLabel.setFont(new Font("Roboto", Font.ITALIC, 14));
            AuxSucurLabel.setForeground(Color.red);
            AuxSucurLabel.setText("Debe escoger una sucursal");  
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuxCantLabel;
    private javax.swing.JLabel AuxDistLabel;
    private javax.swing.JLabel AuxDistrLabel;
    private javax.swing.JLabel AuxLabelMed;
    private javax.swing.JLabel AuxSucurLabel;
    private javax.swing.JButton BotonBorrar;
    private javax.swing.JTextField CanTextField;
    private javax.swing.JLabel CantidadLabel;
    private javax.swing.JLabel DistribLabel;
    private javax.swing.JLabel DistribLabel1;
    private javax.swing.JPanel Fondo;
    private javax.swing.ButtonGroup GrupoDistribuidor;
    private javax.swing.JTextField MedTextField;
    private javax.swing.JLabel NombreLabel1;
    private javax.swing.JRadioButton OpcCemefar;
    private javax.swing.JRadioButton OpcCofarma;
    private javax.swing.JRadioButton OpcEmpsephar;
    private javax.swing.JCheckBox OpcPrincipal;
    private javax.swing.JCheckBox OpcSecundaria;
    private javax.swing.JComboBox<String> TypeMedComBox;
    private javax.swing.JLabel TypeMedLabel;
    private javax.swing.JButton buttonConfir;
    // End of variables declaration//GEN-END:variables
}
